name: Wissance.Hydra CI

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
    
env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Building Wissance.Hydra and running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies 
        run: dotnet restore ./Wissance.Hydra/Wissance.Hydra
      - name: Build Solution
        run: dotnet build --configuration Release ./Wissance.Hydra/Wissance.Hydra
      - name: Run Wissance.Hydra.Tcp.Tests
        run: dotnet test -c Release ./Wissance.Hydra/Wissance.Hydra/Wissance.Hydra.Tcp.Tests/Wissance.Hydra.Tcp.Tests.csproj

